name: Build

on:
  pull_request:
    branches:
      - 'release/*'
      - main
    paths:
      - 'src-tauri/**'
      - 'frontend/**'
      - '!frontend/**/*.css'
      - 'backend/**'
      - '!**.md'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - run: npm ci

      - run: cd backend && npm ci

      - run: cd frontend && npm ci

      # sidecarバイナリをtauri-action実行前に生成
      - name: バックエンドsidecarバイナリ生成
        run: npm run pkg:backend

      # リリース作成なし・署名ありでビルドのみ実行
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          args: '--target aarch64-apple-darwin'
